- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist
  become: yes

- name: Install basic utilities
  apt:
    name:
      - vim
      - wget
      - curl
    state: present
  become: yes
